### ISSUE TITLE
Question on Ibis Telegram Definition

### ISSUE THREAD

**Issue by isalvadori** [Mezgrman/pyIBISv2#3]
Hi! I have just started looking into IBIS, so probably mine is a really stupid question. 
I noticed that in `ibis_protocol.py`, where you define the telegram simple variables `self.DS001b = self._tg("lF{:05d}")` and `self.DS001f = self._tg("lB{:0>7}")`, these seem to be inverted. The "1b" refers to "lF" while the "1f" refers to "lB". Is there a reason for that?

Thanks in advance,

Ilenia

**Comment by CatoLynx** [comment]
Hi Ilenia, actually, this is just how the telegrams are named and defined - it's a standard from the 1980s and there is no real correlation between the name and what is being sent. So this is just a coincidence :)

Also, be advised that all new development will be in [Mezgrman/pyFIS](https://github.com/Mezgrman/pyFIS) from now on!
